### ISSUE TITLE
Installed gd library but still cant install

### ISSUE THREAD

**Issue by mrlolklo** [soyvillareal/Tubeak#3]
im using xampp and i got gd library installed but it still wont work. any tips?

**Comment by soyvillareal** [comment]
You need more than just installing the GD library, please read the documentation carefully and let us know how it goes. If you still encounter issues after this, I'd be happy to help you out.

**Installer:**

<img src="https://soyvillareal.com/docs/tubeak/documentation/images/install-req.png" />
